version: "3"

services:
  app:
    build:
      context: .
    image: paysy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - app-media-files:/app/media/
      - app-static-files:/app/static/
    environment:
      - DJANGO_SUPERUSER_NAME=paysyadmin
      - DJANGO_SUPERUSER_MAIL=paysyadmin@paysy.com
      - DJANGO_SUPERUSER_PASSWORD=passwordTest123
      - ALLOWED_HOST=localhost
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.8-alpine
    links:
      - app
    container_name: nginx_app
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - app-media-files:/app/media/
      - app-static-files:/app/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres-vol:
  app-static-files:
  app-media-files: