# Generated by Django 3.1.3 on 2020-11-07 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGateWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ManyToManyField(related_name='payways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPagosConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id_comercio', models.PositiveIntegerField()),
                ('str_usuario', models.CharField(max_length=255)),
                ('str_clave', models.CharField(max_length=255)),
                ('int_modalidad', models.SmallIntegerField(default=-1)),
                ('payment_url', models.CharField(max_length=255)),
                ('consult_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPagosParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('description', models.CharField(max_length=511)),
                ('payment', models.BooleanField(default=False, help_text='True: payment parameter , False: configuration parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPagosParamVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('zona_pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonapagos')),
                ('zona_pagos_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonapagosparam')),
            ],
        ),
        migrations.AddField(
            model_name='zonapagos',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zona_pagos', to='core.zonapagosconfig'),
        ),
        migrations.AddField(
            model_name='zonapagos',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_pagos', to='core.paygateway'),
        ),
        migrations.AddField(
            model_name='zonapagos',
            name='parameters',
            field=models.ManyToManyField(related_name='zona_pagos', through='core.ZonaPagosParamVal', to='core.ZonaPagosParam'),
        ),
    ]
