# Generated by Django 3.1.3 on 2020-11-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201107_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('document_type', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=127)),
                ('surname', models.CharField(max_length=127)),
                ('phone', models.BigIntegerField()),
                ('extra_field_1', models.CharField(max_length=127)),
                ('extra_field_2', models.CharField(max_length=127)),
                ('extra_field_3', models.CharField(max_length=127)),
                ('extra_field_4', models.CharField(max_length=127)),
                ('extra_field_5', models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='zonapagosparam',
            name='payment',
            field=models.BooleanField(default=False, help_text='True: payment parameter, False: configuration parameter'),
        ),
    ]
