# Generated by Django 3.1.3 on 2020-11-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201110_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, max_length=511, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tex', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pay_details', models.CharField(max_length=511)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.customer')),
                ('paygateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paygateways', to='core.paygateway')),
            ],
        ),
    ]
