# Generated by Django 3.1.3 on 2020-11-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonapagos',
            old_name='parameters',
            new_name='parameter',
        ),
    ]
