# Generated by Django 3.1.3 on 2020-11-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201113_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paygateway',
            new_name='pay_gateway',
        ),
    ]
