# Generated by Django 3.1.3 on 2020-11-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201113_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tex',
            new_name='tax',
        ),
    ]
