# Generated by Django 3.1.3 on 2020-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201116_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='config_name',
            field=models.CharField(default='zona_pagos', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonapagos',
            name='name',
            field=models.CharField(default='zona_pagos', max_length=127, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
