# Generated by Django 3.1.4 on 2020-12-03 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201129_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_pago',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
