# Generated by Django 3.1.4 on 2020-12-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201203_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
