# Generated by Django 3.1.4 on 2020-12-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transactionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionstatus',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
