# Generated by Django 3.1.4 on 2020-12-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201222_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactionstatus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
