# Generated by Django 3.1.4 on 2020-12-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201223_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paygateway',
            options={'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'verbose_name_plural': 'Transaction Status'},
        ),
        migrations.AlterModelOptions(
            name='zonapagos',
            options={'verbose_name_plural': 'Zona Pagos'},
        ),
        migrations.AlterModelOptions(
            name='zonapagosconfig',
            options={'verbose_name_plural': 'Zona Pagos Configurations'},
        ),
        migrations.AlterModelOptions(
            name='zonapagosparam',
            options={'verbose_name_plural': 'Zona Pagos parameters'},
        ),
        migrations.AlterModelOptions(
            name='zonapagosparamval',
            options={'verbose_name_plural': 'Zona Pagos parameters velues'},
        ),
    ]
