# Generated by Django 3.1.4 on 2020-12-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201223_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonapagosparamval',
            options={'verbose_name_plural': 'Zona Pagos parameters values'},
        ),
    ]
